### ISSUE TITLE
Reimplement most of the removed content

### ISSUE THREAD

**Issue by Setnour6** [EndlessEscapade/EndlessEscapade#12]
### Summary

I am proposing to add the content that had been purged after the 1-23-2023 commit that removed many of the content that was known and loved.
I have not yet looked into why that was done, but upon testing the latest master version, I was disappointed.
See the branch here: [Setnour6/EndlessEscapade 1-23-2023_before_purge](https://github.com/Setnour6/EndlessEscapade/tree/1-23-2023_before-purge)

### Reasonings

- This request aims to bring back most of the content that had been removed, that includes the teased content.
- The mod will be completed much faster with the amount of content that resides within the mod, specifically the master branch.
- Not all of the content on the forked repository branch can be added right away. It can be saved until the content needed decides to be ported.

![image](https://github.com/EndlessEscapade/EndlessEscapade/assets/70764728/c9a6a383-935a-4a60-af5d-0b557cf064c5)

**Comment by shnakamura** [comment]
The point of "removing" the content was to refactor the codebase, as it was definitely not the most pleasant in the slightest.

**Comment by Universe-lab** [comment]
Who is this? I've never seen this username on our repo before.

**Comment by shnakamura** [comment]
> Who is this? I've never seen this username on our repo before.

Ex director and creator of the mod, hello!

**Comment by Universe-lab** [comment]
not you idiot

**Comment by shnakamura** [comment]
uni youre so mean

**Comment by shnakamura** [comment]
We appreciate your efforts and intentions, but please dont try to interfere within development without any planning knowledge beforehand.

**Comment by shnakamura** [comment]
Nonetheless, we appreciate your efforts and intentions, but dont interfere within development without prior planning knowledge. If you wish to contribute try reaching us out, we'll be happy to discuss and clear out points 😉

**Comment by Universe-lab** [comment]
> Nonetheless, we appreciate your efforts and intentions, but dont interfere within development without any prior planning knowledge. If you wish to contribute try reaching us out, we'll be happy to discuss and clear out points 😉

Bouncing off this comment. We work and discuss our project almost exclusively through Discord.
If you would like to join our efforts, please DM me. My Discord username is "tyeski".

**Comment by Setnour6** [comment]
> I hope you realize we already have access to all previous commits and versions of this repository and previous codebases, regardless of your branch.

I do. I just wanted to make it easier for you to access the files.

> Nonetheless, we appreciate your efforts and intentions, but dont interfere within development without any prior planning knowledge. If you wish to contribute try reaching us out, we'll be happy to discuss and clear out points 😉

I'll plan things out through more issues and/or discussions and avoid as much interference as possible.

> Bouncing off this comment. We work and discuss our project almost exclusively through Discord.
If you would like to join our efforts, please DM me. My Discord username is "tyeski".

I don't use discord, but since every mod maker I know uses it, I'll think about it. I mainly use Steam.

**Comment by shnakamura** [comment]
I'm glad we were able to sort this out. I'll close this issue, but if you have any doubts or require guidance on contributing feel free to open a new issue. Again, consider shooting us out at Discord if you create one by any chance. Thank you!
