### ISSUE TITLE
Custom moss is only placeable in normal stone

### ISSUE THREAD

**Issue by shnakamura** [EndlessEscapade/EndlessEscapade#5]
### Description

Any custom moss is placeable only in normal stone, though it should be placed only in their desired stone tiles.

* Kelp Moss - Kelp Rock
* Thermal Moss - Basalt

### Reproduction steps

1 - Get any moss.
2 - Attempt to place it on its desired stone.
3 - Re-attempt to place it on normal stone.

**Comment by naakaamura** [comment]
Moss tiles seem to be entirely hardcoded in `Player.PlaceThing_Tiles()`, given the flag:

```cs
if (!canUse || ((tile.active() || flag) && (!Main.tileCut[tile.type] || tile.type == 484) && (tile.type < 373 || tile.type > 375) && tile.type != 461 && createTile != 199 && createTile != 23 && createTile != 2 && createTile != 109 && createTile != 60 && createTile != 70 && !Main.tileMoss[createTile] && !TileID.Sets.BreakableWhenPlacing[tile.type]) || !ItemTimeIsZero || itemAnimation <= 0 || !controlUseItem)
{
    return;
}
```

Perhaps a patch would be necessary, or some other workaround?

**Comment by naakaamura** [comment]
Alternative fix: 

Override `ModItem.UseItem`, and manually check for the tile over the player's cursor placement, and replace if it meets the given requirements.

Downsides:

Does not display item icons as placeable items normally do.

**Comment by naakaamura** [comment]
Note: I accidentally closed this lmfao
